brille24_customer_options_admin:
    resource: |
        alias: brille24.customer_option
        section: admin
        templates: "@SyliusAdmin\\shared\\crud"
        except: ['show']
        redirect: update
        grid: brille24_admin_customer_option_grid
        permission: true
        form:
            type: Brille24\SyliusCustomerOptionsPlugin\Form\CustomerOptionType
    type: sylius.resource

brille24_customer_option_price_import:
    path: '/customer-options/import-prices'
    defaults:
        _controller: 'brille24.sylius_customer_options_plugin.controller.price_import_controller'

brille24_customer_option_price_import_example_file:
    path: '/customer-options/import-prices/example'
    defaults:
        _controller: 'brille24.sylius_customer_options_plugin.controller.price_import_controller:downloadExampleFileAction'
